### ISSUE TITLE
Generator not working with Engines

### ISSUE THREAD

**Issue by cantonic** [meleyal/backbone-on-rails#43]
I have a mountable Engine (Rails 3.2.12) where I tried to install backbone-on-rails, but after running rails g backbone:install it generates a file called nil_class.js.coffee. This is because it cannot find the Engine's name.

**Comment by samarthsikotara** [comment]
@clekstro Can I change a name to bb_engine.js.coffee instead of nil_class.js.coffee?

**Comment by clekstro** [comment]
@samarthsikotara I haven't looked into this since I originally replied, and don't currently use this gem.  Does renaming the file help resolve this issue?

**Comment by samarthsikotara** [comment]
@clekstro Yes It resolves this issue. can I know which gem do you use for bootstrap rails?

**Comment by samarthsikotara** [comment]
@clekstro sorry I typed "bootstrap" by mistake. it's backbone rails. which gem do you use for backbone rails?
