### ISSUE TITLE
Unnecessary Dependencies

### ISSUE THREAD

**Issue by wingrunr21** [meleyal/backbone-on-rails#60]
Hi,

#57 introduced dependencies into the gemspec that are not needed. `activeresource` is not a core rails dependency anymore (since v4) and requiring it forces a large dep (since it pulls in `rails-observers` as well) to be included in the bundle even if it isn't being used. I don't believe this gem requires any dependencies other than `railties`.

That PR also mistakenly blamed the rails dependency in this gemspec for failing to boot. The more likely cause was in `config/application.rb`, rails/all was being required instead of the core parts of rails that were needed.

To test this:

    rails new foobar --skip-active-record
    # Edit Gemfile and add:
    # gem 'backbone-on-rails', '< 1.1.1.0'
    bundle install
    bundle exec rails s

cc/ @brockers

**Comment by courtenay** [comment]
This is fixed, but you should bump a minor version so you don't have to install from git.

**Comment by meleyal** [comment]
Pull request welcome

**Comment by meleyal** [comment]
Pushed 1.1.2.1
