### ISSUE TITLE
JST index templates not available by name

### ISSUE THREAD

**Issue by jkopczyn** [meleyal/backbone-on-rails#69]
I have a Backbone View ReviewsIndex, wrote the template in `templates/reviews/index.jst.ejs`, and attempted to give it the template `JST["reviews/index"]`, but this was said to be undefined. 

Hours later, I discovered the  `JST["reviews"]` alias. Which is nice, but not being able to invoke it by name as expected caused me endless headache. Please fix this undocumented feature.

EDIT: I'm (reluctantly) using Javascript, not Coffeescript.

**Comment by meleyal** [comment]
Hm, not sure why you'd be seeing that. This gem does nothing to modify the way ejs works.

Maybe an issue with `ruby-ejs`?

**Comment by jkopczyn** [comment]
I'll look into that. I'm in a group who were all using a similar setup, and the difference seemed to be that I used your scaffold generation, so I assumed that was the cause.

**Comment by AdeelKamalMalik** [comment]
I am working on http://railscasts.com/episodes/323-backbone-on-rails-part-1. I am in the middle of tutorial but the template: JST['entries/index'] causing issue. Its value is undefined. When I tried to get its value, it show 'undefined.

Please let me know If I am doing something wrong.

**Comment by awendt** [comment]
@jkopczyn I ran into a similar issue without this gem. Can you check your router code please? I suspect it contains this:

    routes: {
      "": "index"
    },

which just means: `reviews/index` will be available under route `reviews`.

**Comment by jkopczyn** [comment]
I definitely did that. Thanks for mentioning it.
