### ISSUE TITLE
issue with eco dependency

### ISSUE THREAD

**Issue by pravi** [meleyal/backbone-on-rails#71]
I am packaging backbone-on-rails for debian and it has a dependency on eco (do you really use it?) but I cannot generate eco.js from the coffee script sources (because any minified javascript should be generated on debian from their sources and eco.js provided by eco-source is minified).

see https://lists.debian.org/debian-ruby/2015/06/msg00038.html for errors. Can you suggest how to proceed?

**Comment by meleyal** [comment]
`eco` is the templating language when using coffeescript, while `ejs` is used for javascript. Currently the gem relies on both `ejs` and `eco` as I couldn't find a way to conditionally depend on one or the other.

eco.js is minified here: https://github.com/sstephenson/eco/blob/0d60edbf4ee76beaade73368de412b5fee7edba7/Cakefile#L80

The best I can suggest is to open an issue / pull request to also include an unminified version of `eco.js` in the build step.

**Comment by pravi** [comment]
Thanks for the reply. Last commit of eco is in 2012 so I don't know if I can get that change done there.

**Comment by pravi** [comment]
https://github.com/sstephenson/eco/issues/66 Can we use ECT?

**Comment by meleyal** [comment]
The syntax looks compatible, but apparently no sprockets support :(
https://github.com/baryshev/ect/issues/32
